### ISSUE TITLE
Streaming Texture panel is only displayed when render device is set to Eevee

### ISSUE THREAD

**Issue by baronlanteigne** [maybites/blender.script.spout#10]
The plugin functions just fine in material preview and solid when using Cycles. The only limitation is that you can't access the texture panel unless you change the render engine to Eevee. It's not a big deal but it's good to know.

**Comment by maybites** [comment]
can you make a quick test?

on line 

https://github.com/maybites/blender.script.spout/blob/139e914620bc720baa6bfb479061deee1ad27b29/__init__.py#L157

can you add 'CYCLES' and see if this does the trick?

**Comment by baronlanteigne** [comment]
It works! Thanks!
