### ISSUE TITLE
Color management settings not respected 

### ISSUE THREAD

**Issue by MadlyFX** [maybites/blender.script.spout#11]
This is likely a bug with Blender, but just in case it's not, I'm posting here as well.

https://developer.blender.org/T84227

Using Blender 2.93, the Spout output does not respect any of the color management settings associated with it. This includes the display device, exposure and gamma settings. This is problematic, as it defaults to Raw which produces an incorrect image.

![Inkeddraw_view3d_LI](https://user-images.githubusercontent.com/4896705/115769127-cc0cfd00-a370-11eb-95f0-c6da2a5ff1e6.jpg)

**Comment by maybites** [comment]
Looking at the bugreport it seems to be the issue: If the color corrections aren't applied, there is not much I can do here. This addon is based on the mentioned code example and just passes on the reference of the rendered texture to spout instead.

**Comment by MadlyFX** [comment]
Completely fair. Feel free to close this. And maybe we can post on the bug report to try and get it fixed :)

**Comment by maybites** [comment]
How do plan to use the spout addon? you mentioned you wanna use it for virtual production, but maybe you can elaborate on your setup?

**Comment by MadlyFX** [comment]
Sure! We provide in-camera set extension services (Mandalorian-style) for film and TV in Chicago, and are trying to get away from Unreal.

Right now the plan is to have Blender Spout the camera to Lightact. Both Lightact and Blender will receive camera tracking data, which Blender will use to render the correct perspective and Lightact will use to project that image onto a mesh representing an LED screen. That image then goes out to the LED screen and and appears correct to the physical camera.

The trick is the LED processors used can only output a 4K stream--but we deal with resolutions way beyond 4K, so we need a way to render parts of the same scene across multiple computers and have their outputs merged with Quadro sync. That's not something I expect from this plugin, but it's where I'm headed towards.

**Comment by maybites** [comment]
why do you wanna leave unreal?

**Comment by MadlyFX** [comment]
UE is great for quick prototypes, but Epic has an MO of adding an untested feature, abandoning it, and then leaving the community to pick up the slack. As a result, many of the systems they've implemented that are required for this are unstable or simply unusable.

Additionally, the deeper we get into this, the more it's "game engine-ness" is a restriction. We're not making a game, so there are a lot of things that are entirely unnecessary or get in the way--needless complexity and bloat. Blender has a number of features that would be extremely useful (simulation, modeling, etc.) that UE doesn't have.

If we need to put development work into an engine to make it usable, I'd much rather give back to the Blender community than to the Epic games monolith.

**Comment by maybites** [comment]
weirdly enough, I am unable to run the addon myself anymore... the script complains about a missing dll. But I have the SpoudSDK.pyd where its supposed to be. What did you do to make it work on your machine?

**Comment by MadlyFX** [comment]
> 
> 
> weirdly enough, I am unable to run the addon myself anymore... the script complains about a missing dll. But I have the SpoudSDK.pyd where its supposed to be. What did you do to make it work on your machine?

Are you using Blender 3.0.0, or one of the newer beta branches? If so, they moved to Python 3.9 and won't see a library compiled with 3.7.

**Comment by maybites** [comment]
nope, its still 2.92..

**Comment by MadlyFX** [comment]
> 
> 
> nope, its still 2.92..

Well that's odd, I just tried to reinstall it and it works for me. I'm on 2.92 as well. Maybe it's a DLL not related to the plugin?

**Comment by maybites** [comment]
this thread points to an answer: https://blender.stackexchange.com/a/210753

If someone can provide a code snipplet that converts the texture (aka the function transformRGBSpace())

```
def draw():
    ...
    offscreen.draw_view3d(
        scene,
        context.view_layer,
        context.space_data,
        context.region,
        view_matrix,
        projection_matrix)

>> additional conversion  offscreen.color_texture from linear-RGB-space to color-managment-RGB-space
    color-managed-texture = transformRGBSpace(offscreen.color_texture)
<<

    draw_texture_2d(color-managed-texture, (10, 10), WIDTH, HEIGHT)
```

I am willing to implement it to the addon.

cheers

martin

**Comment by MadlyFX** [comment]
It might be worth holding off until the Vulkan integration, since apparently the API is changing anyway.

**Comment by MadlyFX** [comment]
Looks like the fine Blender folks fixed this: https://developer.blender.org/D11645

**Comment by maybites** [comment]
cool. I will make a new branch for 3.0.0 then and implement it there..

**Comment by coffeebreak42** [comment]
Pinging this @maybites 
I'm trying to use this plugin, but the colors are off... right now the image I'm getting from spout is much darker and different than what is in my blender viewport.  See attached spout vs blender viewport.  ![test1](https://user-images.githubusercontent.com/38296141/149853633-9f0adcb1-b45d-466b-84a1-e4505eb60dac.jpg)
![test2](https://user-images.githubusercontent.com/38296141/149853654-d5a460f5-a0c0-464c-b064-9afd830e4862.jpg)

**Comment by coffeebreak42** [comment]
Okay I solved the problem. Please push these changes, I do not know how to recommend the changes, I'm new to GitHub. Basically the blender ppl set do_color_management to FALSE by default for some reason. You have to manually set it to TRUE for color_management to be applied correctly. 
SOLUTION IN BOLD, within the _init_.py. 

    offscreen.draw_view3d(
        scene,
        context.view_layer,
        context.space_data,
        context.region,
        view_matrix,
        projection_matrix,
	**do_color_management=True)**

**Comment by maybites** [comment]
there is already a branch with this fix.
