### ISSUE TITLE
not working for me no matter what i try

### ISSUE THREAD

**Issue by Danielhungary** [maybites/blender.script.spout#13]

**Comment by Danielhungary** [comment]
addon_utils.py"
line 351
mod= __import__(module_name)
ModuleNotFoundError: No module named 'blender'

i run 2.93.5

**Comment by maybites** [comment]
which zip did you download?

**Comment by Danielhungary** [comment]
The latest one. The most obvious one i did not try to dienload an earlier
version. If you need, i can attach a screenshot of what blender says, but
it is a longer version of what i already posted :)

Thanks by the way i am really grateful!

maybites ***@***.***> ezt írta (időpont: 2021. okt. 18., Hét
23:50):

**Comment by maybites** [comment]
do be sure: from here? https://github.com/maybites/blender.script.spout/releases

**Comment by Danielhungary** [comment]
Yes! :) from there

maybites ***@***.***> ezt írta (időpont: 2021. okt. 19., Ke
9:36):

**Comment by maybites** [comment]
whats the folder name the spout plugin resides?

**Comment by Danielhungary** [comment]
I followed your instructions, even tried to put the files and folder in the
blender 2.93 program files structure. So in both cases it appeared in the
addon tab but when i try to tick the box it gives me that error message i
reported on the github page. If is in both location than blender reminds me
of that so i need to remove one of them.

So yes, i created a folder nameg blender in my documents folder. Inside
this blender folder there was a scripts folder with addons and modules in
it. I copied the unzipped folder in the addon and the script in the
modules.

maybites ***@***.***> ezt írta (időpont: 2021. okt. 19., Ke
9:43):

**Comment by maybites** [comment]
can you show me the folder structure?

**Comment by Danielhungary** [comment]
There

maybites ***@***.***> ezt írta (időpont: 2021. okt. 19., Ke
9:54):

**Comment by maybites** [comment]
?

**Comment by Danielhungary** [comment]
Did you get the picture? Do you have a gmai account or any other account?
Which is able to receive emails with images attached?

maybites ***@***.***> ezt írta (időpont: 2021. okt. 19., Ke
10:13):

**Comment by maybites** [comment]
not sure what u are doing. it is possible to upload images here.

**Comment by Danielhungary** [comment]
I tried to send it via e mail

maybites ***@***.***> ezt írta (időpont: 2021. okt. 19., Ke
10:27):

**Comment by Danielhungary** [comment]
![spout](https://user-images.githubusercontent.com/92754722/138137687-4de78483-d7f4-463b-8de3-db2124f3a3ac.png)
 There is a picture of the issue
![spout_](https://user-images.githubusercontent.com/92754722/138137979-61a40766-24ce-46fd-819d-fd958070ee17.png)

**Comment by Danielhungary** [comment]
hope this helps!?

**Comment by maybites** [comment]
what is inside addons?

**Comment by Danielhungary** [comment]
The unzipped folder

maybites ***@***.***> ezt írta (időpont: 2021. okt. 20., Sze
20:18):

**Comment by maybites** [comment]
whats his name?

**Comment by Danielhungary** [comment]
:D haha, got it working somehow!

love your patience. Not sure what made the problem but i renamed the unzipped folder and copied the files everywhere possible. :P

**Comment by Danielhungary** [comment]
hello! Is there a way to use transparency with it?

**Comment by maybites** [comment]
spout has an alpha channel, but I am not sure if blender render to texture is able to create one.

**Comment by digi2022** [comment]
> :D haha, got it working somehow!
> 
> love your patience. Not sure what made the problem but i renamed the unzipped folder and copied the files everywhere possible. :P

Hello - Do you happen to recall what you did exactly to get this working?  I am getting the same error message, you mentioned renaming the zip file?   I can get it as far as you did and then the brick wall.   Pics attached showing error.   
 Appreciate any help if you recall what steps you did to get it working.   Thanks 
![spout error 1](https://user-images.githubusercontent.com/97780135/149613520-98e7acd2-6049-41b9-b40a-0dca02963e96.PNG)
![spout error 2](https://user-images.githubusercontent.com/97780135/149613522-9e97875b-8c53-4327-b233-80bba1061c24.PNG)

**Comment by maybites** [comment]
did you download the add-on from the releases? https://github.com/maybites/blender.script.spout/releases

**Comment by coffeebreak42** [comment]
I HAD THIS PROBLEM AND SOLVED IT. 

All you have to do is rename the folder blender.script.spout-1.2 to something else without a "."

For the creator maybites, I think the "." in the file name is messing something up. Just a guess. But I was getting the same problem, after changing the folder name (residing in addons) to something else, like "blenderpythonscript" it worked. 

Let me know if that works for anyone else.

**Comment by maybites** [comment]
`For the creator maybites, I think the "." in the file name is messing something up`

I am aware of it. But I don't want to rename the repo anymore.

the readme points to the download link inside the release, where I renamed the folder to avoid this problem.

**Comment by Shoubaka** [comment]
Hi,
Thanks a lot for this add-on.
I Don't understand why but i didn't receive the streaming texture to spoud receiver.
I don't understand what i'm doing wrong.
![Capture](https://user-images.githubusercontent.com/83662098/160474724-94f7c419-9f70-4d72-a28a-b7035520b58b.PNG)

**Comment by maybites** [comment]
tricky. do you have the correct library inside the modules folder?

**Comment by Shoubaka** [comment]
Wouah, thanks for your fast answer.
I don't know..
here is my folder:
![folder](https://user-images.githubusercontent.com/83662098/160488077-0d98f258-cf1c-4d77-bdf7-990a94b8db81.JPG)

**Comment by maybites** [comment]
ok, you installed the latest release but I hadn't pushed the code with the readme to the current master.

please read the readme carfully and replace the SpoutGL folder accordingly.

**Comment by Moykul** [comment]
Hi,

Having issues installing addon any ideas?


Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\scripts\addons\spout\__init__.py", line 31, in <module>
    import SpoutGL
  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\scripts\modules\SpoutGL\__init__.py", line 1, in <module>
    from ._spoutgl import *
ModuleNotFoundError: No module named 'SpoutGL._spoutgl'

**Comment by Moykul** [comment]
> Hi,
> 
> Having issues installing addon any ideas?
> 
> Traceback (most recent call last): File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\scripts\modules\addon_utils.py", line 351, in enable mod = **import**(module_name) File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\scripts\addons\spout__init__.py", line 31, in import SpoutGL File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\scripts\modules\SpoutGL__init__.py", line 1, in from ._spoutgl import * ModuleNotFoundError: No module named 'SpoutGL._spoutgl'

Ok, humblest apologies! wrong https://pypi.org/project/SpoutGL/#files python version
blender 3.1 uses python environment 3.10.2
