### ISSUE TITLE
Potential Problem with SpoutSDK.pyd

### ISSUE THREAD

**Issue by HeadRAM** [maybites/blender.script.spout#14]
I have the file structure set up correctly:

Documents/blender/scripts/modules

the SpoutSDK.pyd is placed in this modules folder. I am using Blender 2.93 however tried to install using Blender 3.0 and received the same error message:

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\Tucker_Grindstaff\Documents\blender\scripts\addons\spout\__init__.py", line 31, in <module>
    import SpoutSDK
ImportError: DLL load failed while importing SpoutSDK: The specified module could not be found.

**Comment by maybites** [comment]
the spout plugin has to reside inside:

C:\xxx\blender\scripts\addons\spout\...

and with blender 2.9.3 upwards you need to have the SpoutSDK.pyd compiled for python 3.9: https://github.com/maybites/blender.script.spout/releases/tag/Python_3.9
