### ISSUE TITLE
Transparent Background

### ISSUE THREAD

**Issue by chabad360** [maybites/blender.script.spout#15]
From what I'm able to see, spout supports an alpha channel. Would it be possible for this to send a transparent background when it is enabled in Blender?

**Comment by maybites** [comment]
I don't think so. The API I am using doesn't hint at that possibility. The limitation seems to be on blender's side.

**Comment by chabad360** [comment]
Is it perhaps possible to output the alpha layer separately (to use it as a matte)?

**Comment by maybites** [comment]
I am using this approach:

https://docs.blender.org/api/master/gpu.html#rendering-the-3d-view-into-a-texture

if you see a way to do this, please let me know.
