### ISSUE TITLE
Problem with custom Workspaces

### ISSUE THREAD

**Issue by BlandSauce** [maybites/blender.script.spout#16]
The name of a screen used by a workspace may not match the workspace name, especially with workspaces with non-default names, and may not work when selected for the Shading option.

Changing \_\_init\_\_.py line 100 from:
`        for area in bpy.data.screens[guivars.workspace].areas:`
to
`        for area in bpy.data.workspaces[guivars.workspace].screens[0].areas:`
appears to fix this.

I say "appears" because it's fixed it for my use case, but I haven't tested much outside of that.

**Comment by maybites** [comment]
thank you for pointing this out. I will fix.

**Comment by maybites** [comment]
fixed with 1cae75402c95e83b8a776129f6ae11f3b3370b55 [1cae754]
