### ISSUE TITLE
Poor performance on blender 3.2.1

### ISSUE THREAD

**Issue by baronlanteigne** [maybites/blender.script.spout#18]
I'm getting very poor performance with Blender 3.2.1 when streaming a 720x720 texture. Viewport runs eevee at about 40fps and it drops to 2fps when I stream it out. Not sure what I did wrong. I used this addon back in 2020 and it was flawless!

**Comment by maybites** [comment]
Nothing has substantially changed inside the addon to explain this change.

can you provide me the version of the addon you are using right now 

and 

the blender and addon version that provided you with the expected performance in 2020?
