### ISSUE TITLE
Syntax Error when enabling addon in blender 2.79b

### ISSUE THREAD

**Issue by l00f00** [maybites/blender.script.spout#2]
Hi, i'm getting a syntax error while enabling the addon in blender 2.79b

https://pasteboard.co/IfgwlzM.png

`class TEXS_PG_camera_texshare_settings(bpy.types.PropertyGroup):
    enable : bpy.props.BoolProperty(
        name = "enable",
        default = 0,
        description = "enables the texture streaming", 
        update=texshare_main
    )`

i also tried in 2.8, the addon looks enabled, but can't find Panel to the Camera properties called 'Streaming Texture', anywhere :/ any hint?

Thanks for the effort you are putting in this awsome addon!

**Comment by maybites** [comment]
This plugin only works with blender 2.8.

-> select the camera, go to properties panel, select object data tab, there it should be...

**Comment by l00f00** [comment]
Thank you for the quick answer ! 
Now i see the Streaming Texture with a toggle to enable disable the sender in 2.8.

Testing with spout sender/receiver and Touch Designer sadly i see empty stream coming in both in touchdesigner and spout receiver,

![Cattura](https://user-images.githubusercontent.com/43296799/57983098-5db9b480-7a4e-11e9-928a-abc776578acd.JPG)

with demo spout sender the stream is flawlessly received

![Cattura2](https://user-images.githubusercontent.com/43296799/57983171-1849b700-7a4f-11e9-9a57-656c8f799430.JPG)


These are my specs from spout diagnostic tab

[Spout Receiver (Vers 2.018)
DirectX 9.0c available
Intel(R) HD Graphics Family (Display)
Microsoft Basic Render Driver (Secondary)
Current adapter : Intel
NV_DX_interop extension available
DirectX 11 Texture share mode]

Thank you in advance for the help!

**Comment by maybites** [comment]
it looks as if you are in blender image editor. that wouldn't work. you need to be in 3dviewport.

**Comment by l00f00** [comment]
ah sorry that was just for reference pourpose, here is another screenshot, i really can't get what mistake i'm making, i guess maybe is because i have a self contained blender 2.8 version, i just extraced it into a folder
![Cattura3](https://user-images.githubusercontent.com/43296799/57983828-7f1e9e80-7a56-11e9-8f0e-48d10b21b9ad.JPG)

**Comment by newemka** [comment]
Hey, you need to try lookdev, with matcap

**Comment by l00f00** [comment]
Ok, sorry i'm not very good at blender, using eevee, cycles or internal? this is the rendered output straight from f12
![output](https://user-images.githubusercontent.com/43296799/57984469-539eb280-7a5c-11e9-88c0-d41df9a0d50c.png)

![Cattura4](https://user-images.githubusercontent.com/43296799/57984425-facf1a00-7a5b-11e9-92dd-9696502c80fc.JPG)

**Comment by newemka** [comment]
i'm using eevee, but i got it working only in basic solid shading mode
![basic](https://user-images.githubusercontent.com/3755089/57984640-1fc48c80-7a5e-11e9-97c1-c976634703c7.jpg)

**Comment by maybites** [comment]
ideally EEVEE, but currently it works only with solid and wireframe shading mode because of a driver bug (with nvidia cards)

**Comment by l00f00** [comment]
OK! maybe it's just a problem with my gpu! i'm not on an nvidia graphic card, currently it's a pretty old intel iris HD Graphics 4400 , rendering is performed on CPU on this machine because of no CUDA available; i think we can consider the issue closed if this is the matter of why it doesn't plot any image to the receiver
![Cattura5](https://user-images.githubusercontent.com/43296799/57984832-f60c6500-7a5f-11e9-88d2-d5cef970a649.JPG)
Thank you for your help and support Guys that is much appreciated! Keep up with the good job with this nice piece of software

**Comment by maybites** [comment]
Hard to say. Spout has nothing to do with the classical rendering, it uses render to texture functionality. try the following:

https://docs.blender.org/api/blender2.8/gpu.html#rendering-the-3d-view-into-a-texture

instructions: https://docs.blender.org/api/blender2.8/gpu.html#examples

start with the default scene and render set to eevee. it should show the rendered texture inside the 3d viewer.

**Comment by l00f00** [comment]
Runned the script on the page following the instruction provided, they all have results on the 3d view except the one for render to texture, do i have to apply the texture to something like a plane?  ![Cattura6](https://user-images.githubusercontent.com/43296799/57985407-e85add80-7a67-11e9-8a62-78e4778e7604.JPG)

**Comment by maybites** [comment]
restart blender and just run the render to texture script. once you put your cursor into the viewport window the texture should appear.

**Comment by l00f00** [comment]
with just the cursor in the viewport nothing is happening, but if i click on che cube i get 
![image](https://user-images.githubusercontent.com/43296799/57985518-57850180-7a69-11e9-8230-d3b9e23a5b68.png)

**Comment by maybites** [comment]
that's strange. now I am clueless. sorry.

**Comment by l00f00** [comment]
tomorrow i'll try to repeat the process in an earlier version of 2.8 maybe it helps debugging thanks man!

**Comment by maybites** [comment]
which version of blender do you use?

**Comment by maybites** [comment]
there is an issue with the latest blender. they changed the api and the render to texture example is broken, and thus my script, too.

**Comment by l00f00** [comment]
![image](https://user-images.githubusercontent.com/43296799/57986157-843d1700-7a71-11e9-9dfe-16bd194f6a1b.png) so thats the thing! mine is latest beta, wich release would work?

**Comment by maybites** [comment]
not sure, maybe a week old? I don't know where to download it, though.

**Comment by maybites** [comment]
the latest release should have fixed this issue.
