### ISSUE TITLE
alpha from blender to TD

### ISSUE THREAD

**Issue by jhoepffner** [maybites/blender.script.spout#20]
Hello, I export Blender eevee with alpha background activated but there is no alpha in TD reception, I have to activate something special to obtain it?
Thank you,
Jacques Hoepffner

**Comment by maybites** [comment]
To my knowledge currently not possible: https://github.com/maybites/blender.script.spout/issues/15

**Comment by jhoepffner** [comment]
Thank you for your answer. I like the possibilities open by your add-on.
Beside it I use OSD and Spout with Unity D where you can import and export texture via Spout, with alpha layer.
Do you hink it could be possible with Blender? It would be so great!
Have a nice day,
Jacques

**Comment by maybites** [comment]
> Do you hink it could be possible with Blender?

probably, but beyond my capabilities.
