### ISSUE TITLE
error 3.4 blender

### ISSUE THREAD

**Issue by sonnyobrien** [maybites/blender.script.spout#22]
![image](https://user-images.githubusercontent.com/27340727/223894063-bd57dd41-dfb1-4cb2-af34-438a954f09dc.png)

**Comment by maybites** [comment]
not helpfull

**Comment by VeissieV** [comment]
I get the same error with the Blender 3.5 beta when trying to activate the addon. The console doesn't show any other info. I'm using the 3.1.0 version in Windows 11. The addon shows version 3.0.0 in preferences still. I know this is somewhat common when creators don't update the version number, but figured it's worth mentioning. Before trying to update to 3.1.0 I disabled the addon, rebooted blender then hit remove, rebooted blender again, and then tried installing 3.1.0 just to be sure.

Thanks for your work on this addon. I had a lot of fun with it when I had it working.

**Comment by maybites** [comment]
still not helpfull: please adhere to these standards. I need clear steps to be able to reproduce:

https://wiki.blender.org/wiki/Process/Bug_Reports

**Comment by maybites** [comment]
Made a quick test with blender 3.6 alpha on Windows 11 and it works just fine.

**Comment by TheoDelamare** [comment]
hello, i just changed the spout addon folder name in my addon folder from "spout_3.0.1" to "spout" then restarted blender and it worked just fine
