### ISSUE TITLE
The addon doesn't work because of folder naming problem

### ISSUE THREAD

**Issue by climoge** [maybites/blender.script.spout#23]
Hello !

Since you change the code to support Syphon, the addon is broken.
In `FrameBufferSharingServer.py` you import `spyphon.fbs.syphon.SyphonServer` (line 30) and `spyphon.fbs.spout.SpoutServer` (line 33).
In `SpoutServer.py` you import `spyphon.fbs.FrameBufferSharingServer` (line 9).
In `SyphonServer.py` you import `spyphon.fbs.FrameBufferSharingServer` (line 9).

But your addon's folder is named `spout`, so python cannot find the module.
If you rename the folder `spyphon`, python will throw an error because you import `spout.fbs.FrameBufferSharingServer` in `operators.py` (line 12)

So you can either rename the folder `spyphon` and change the import in `operators.py`; or you can make all you imports relative.

If you want I can submit a PR with the `import` modifications.

**Comment by maybites** [comment]
mybad - you are correct. I had the development folder for the spyphon project in all my installation tests present and didn't notice this flaw.

I will fixit asap.

**Comment by maybites** [comment]
should be fixed with 

https://github.com/maybites/blender.script.spout/commit/51dbf1d5cdebf71d8e7fc0ba3fee0173377c7645
