### ISSUE TITLE
alpha support

### ISSUE THREAD

**Issue by fasoric** [maybites/blender.script.spout#26]
not sure if it's an issue or a limitation, but enabling transparent film makes the background go mid gray. if alpha could be somehow supported it would be crazy, but if not, at least having a plain black bg would probably be more correct.

**Comment by maybites** [comment]
not much I can do about this. It seams the Offline Render Feature the Python API exposes renders without transparency:

https://docs.blender.org/api/master/gpu.html#rendering-the-3d-view-into-a-texture
