### ISSUE TITLE
spout export with alpha background

### ISSUE THREAD

**Issue by jhoepffner** [maybites/blender.script.spout#27]
Hello,
I try to export a moving cube from Blender to TouchDesigner with alpha background.
I activated Render/Film/Transparency. In TD, the image is tagged 8 bits RGBA but the image show a grey background.
Thank you in advance,
Jacques

**Comment by maybites** [comment]
Hi
I don't know how I can make alpha work. For the time beeing it has its limitations.
cheers
martin
