### ISSUE TITLE
Broken with today blender build

### ISSUE THREAD

**Issue by newemka** [maybites/blender.script.spout#3]
I only get a black image in spout receiver with today build blender-2.80.0-git.06c4139a6833-windows64
Fortunately I pulled blender-2.80.0-git.ee0d8426ab6d-windows64 off my trash and the script is working.

**Comment by maybites** [comment]
can you make the following test?

https://docs.blender.org/api/blender2.8/gpu.html#rendering-the-3d-view-into-a-texture

instructions: https://docs.blender.org/api/blender2.8/gpu.html#examples

start with the default scene and render set to eevee. it should show the rendered texture inside the 3d viewer.

**Comment by maybites** [comment]
it looks as if the latest blender has an api change and the render to texture script is broken. I will updated a bug report: https://developer.blender.org/T61768

**Comment by newemka** [comment]
I did the test and I confirm that nothing is appearing with blender-2.80.0-git.06c4139a6833-windows64

**Comment by maybites** [comment]
ok, this should be fixed with the latest release 1.2.

**Comment by newemka** [comment]
It's working again! yay!
