### ISSUE TITLE
Error when enable the addon

### ISSUE THREAD

**Issue by anodin** [maybites/blender.script.spout#30]
![image](https://github.com/maybites/blender-texture-sharing/assets/8354232/a81faad4-4092-44b2-9b16-1185aba2de6d)
I get this error when i try to enable the addon
Blender 4.1 on win 11 . blender-texture-sharing-6.0.4
Any cue ?
I try with many blender 3x and 4x  and  blender-texture-sharing-6.0.0
Thx, i really want to try it !

**Comment by maybites** [comment]
ouch. Yes, sorry. Its the dots in the module name.

uninstall it and try it again:

https://github.com/maybites/blender-texture-sharing/releases/download/V6.0.5/blender-texture-sharing.zip

**Comment by anodin** [comment]
Perfect it works ! 
I just try with Spout (because personnal problem with NDI and my computer)
Congrats, to let choose the resolution by camera ! wow it's a game chager for me !
