### ISSUE TITLE
Receiving textures server OFF

### ISSUE THREAD

**Issue by Naamahhh** [maybites/blender.script.spout#31]
Sending works, but I am trying to get the image back to Blender from TouchDesigner and it shows up on Spout Receiver, but not the Blender "Receive Textures".  
Using Blender 4.0, tried updating, restart pc, re-adding the addon.
![spout receiver not working](https://github.com/maybites/blender-texture-sharing/assets/68248025/1fdb8666-02b9-4f0a-aece-ac8d2cc5fe73)

**Comment by newemka** [comment]
The [State of Development](https://github.com/maybites/blender-texture-sharing?tab=readme-ov-file#state-of-development) shows that Windows Spout Receiver is not available yet.

You should try with NDI Receiver.

**Comment by Naamahhh** [comment]
Ah I see, my bad for not noticing that! Thanks for the info/plugin and I shall try that then.
