### ISSUE TITLE
How to stream texture updates in EEVEE?

### ISSUE THREAD

**Issue by zumpchke** [maybites/blender.script.spout#32]
I have an input animation from Syphon but when I press play in timeline the texture doesn't update.

**Comment by zumpchke** [comment]
I might be stupid but I can't figure out how to get the texture to update in realtime in the viewport. If I click and move something in the viewport it then changes.

Using blender 4.1

**Comment by maybites** [comment]
This is a known issue. I don't have yet figured out how to fix this.

**Comment by zumpchke** [comment]
@maybites thank you for the update.

Is there any way to get texture updates other than viewport mode?

**Comment by momagit** [comment]
@zumpchke to update the received texture on every new frame of the timeline add the following after line 221 of the 
operators.py file:
bpy.app.handlers.frame_change_pre.append(write_handler)
this will probably give you very slow playback but you could decrease the resolution of your source material to improve performance if this is an option for your usecase.

**Comment by maybites** [comment]
this should be fixed with the latest..
