### ISSUE TITLE
Cant select Input Spout in panel

### ISSUE THREAD

**Issue by mariance95** [maybites/blender.script.spout#36]
Hi! Im streaming a Spout Texture thru resolume and I want it to show in Blender. But the spout server FROM resolume is not showing, not even the server from the blender camera. It does work otherway (From Blender Camera to Resolume) but I cant get my resolume output to show in the server panel in Blender. Using blender 3.6  and tried with newest blender version 4.1 also

**Comment by maybites** [comment]
Spout is not supported yet. Try NDI instead. Though don't keep your hopes high. Its performcance sucks and there are other [issues](https://github.com/maybites/blender-texture-sharing/issues/34).
