### ISSUE TITLE
Alpha output

### ISSUE THREAD

**Issue by FellowSufferer** [maybites/blender.script.spout#37]
Can anyone suggest a way to output an alpha channel, to remove background (with the "Transparent" setting in the Film section)? Is it even possible right now in a single output?

**Comment by maybites** [comment]
Its a known issue and I am unaware of a solution. Blender would have to make API changes to make this possible..

**Comment by FellowSufferer** [comment]
It's a shame. I made a hacky solution - using a green plane in the background of a scene and keying it out in OBS, so it sorta works %).
