### ISSUE TITLE
Spout SDK error

### ISSUE THREAD

**Issue by driftnote** [maybites/blender.script.spout#4]
Had the addon working yesterday with an older 2.8 build. Opened Blender today, same build, and kept getting an error message.
![Annotation 2019-05-20 134611](https://user-images.githubusercontent.com/7478488/58041408-0a0aa200-7b06-11e9-9daf-4081ede345bb.png)

I uninstalled it. followed the steps again to install it but i keep getting the same message
![Annotation 2019-05-20 134625](https://user-images.githubusercontent.com/7478488/58041505-40e0b800-7b06-11e9-8f46-6eaa10ca7338.png)

I have tried moving the SpoutSDK from scripts/modules folder i created as suggested in the instructions to the 'modules' inside of the blender build and still get the same error message.

any ideas what i am doing wrong?

**Comment by maybites** [comment]
whats the message?

**Comment by driftnote** [comment]
> whats the message?

I attached a screenshot. it says "This plugin works only if the Spout.pyd is inside '-/scripts/modules'"

I do have that file in the modules folders and i've tried to move it within the modules folder inside of the blender build.

**Comment by maybites** [comment]
this is not an error message, rather an installation hint. more importantly: is the plugin working?

**Comment by driftnote** [comment]
> this is not an error message, rather an installation hint. more importantly: is the plugin working?

Yes, you are right. It is a hint. But no, the panel in the camera properties called 'Streaming Texture' does not show up so I have no access to the plugin inside Blender UI

**Comment by maybites** [comment]
any errors in the console?

**Comment by driftnote** [comment]
sorry for the late reply. No there are no errors in the console. Just that hint message on the addon pane and there is no 'Streaming texture" in the camera properties panel. Why's do you think it is not seeing the  the Spout.pyd file?

**Comment by maybites** [comment]
no idea. it works on all the machines I have installed it so far. did you check the others [issues](https://github.com/maybites/blender.script.spout/issues)?
