### ISSUE TITLE
Transparency on Spout Output

### ISSUE THREAD

**Issue by UnderSampled** [maybites/blender.script.spout#40]
My intention for using TextureSharing is to overlay the output from Blender into OBS in real time. I should be able go from OBS into Blender and back again, once the spout receiver is working, but my original expectation was to set a transparent world background and then use transparency on the spout. Would this be possible?

I'm actually trying to do this compositing to add 3D objects to my camera video, so it would be really cool if there was some way to do camera tracking, but obviously that is beyond the scope of this project. Just wanted to give some context, and hear any ideas you may have on better ways to do this.

**Comment by maybites** [comment]
Transparency is currently not possible AFAIK. Thats a limitation of the blender API.

Tracking camera and overlaying it with 3d objects sound like Augmented Reality. So maybe look into those toolkits:

https://developer.apple.com/augmented-reality/arkit/

https://developers.google.com/ar

it should be possible to send the result to OBS via https://www.airserver.com/

**Comment by Waldehyd** [comment]
Would it be possible to output the compositor to create a greensceen and mask it in OBS?

**Comment by maybites** [comment]
maybe with the realtime compositor... I never used it.

**Comment by jlai** [comment]
Adding draw_background=False to https://github.com/maybites/TextureSharing/blob/master/operators.py#L107 seems to work

OBS Studio with Spout capture on top, static image layer below

![Screenshot 2024-09-16 00-24-24](https://github.com/user-attachments/assets/ce0b4358-f8be-4441-b89e-85aca4dd815c)

**Comment by maybites** [comment]
Nice. I will implement a flag in the GUI to add this functionality. Thanks for figuring this out!

**Comment by UnderSampled** [comment]
Very cool. Looking forward to trying it!

**Comment by maybites** [comment]
check out V7.0.0 -> https://github.com/maybites/TextureSharing/archive/refs/heads/master.zip
