### ISSUE TITLE
Constant crashes on Blender 4.1.1

### ISSUE THREAD

**Issue by Waldehyd** [maybites/blender.script.spout#41]
On Blender 4.1.1, (stable) the Addon causes regular crashes. I attached the crashlog.

[BlenderLog.txt](https://github.com/user-attachments/files/17006305/BlenderLog.txt)

**Comment by maybites** [comment]
can you test with https://github.com/maybites/TextureSharing/releases/tag/V6.0.5?

I will have a look at it in a few days on a windows machine.

**Comment by Waldehyd** [comment]
I used V6.0.5, sorry should've clarified.

**Comment by maybites** [comment]
ok. 

Can you describe all the steps that reliably produce the crash?

**Comment by Waldehyd** [comment]
[Vtuber_4.1_CutBody_increasedShapeKeys.blend.zip](https://github.com/user-attachments/files/17017951/Vtuber_4.1_CutBody_increasedShapeKeys.blend.zip)

Hard to tell, it's really random. I attached the blendfile. Open it in 4.1.1, activate the TextureStreaming, go to shading and move around the viewport. I also use OBS to capture, but I assume its not realted as its only listening?

**Comment by maybites** [comment]
Does it also happen with 4.2.1?

**Comment by maybites** [comment]
please test with the latest -> https://github.com/maybites/TextureSharing/archive/refs/heads/master.zip

**Comment by Waldehyd** [comment]
This gives me an error on Install:

Traceback (most recent call last):
  File "D:\Programme\Blender\stable\blender-4.1.1-stable.e1743a0317bc\4.1\scripts\modules\addon_utils.py", line 444, in enable
    mod.register()
  File "C:\Users\Waldo\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\TextureSharing-master\__init__.py", line 61, in register
    operators.add_streaming_type_spout(operators.fb_directories)
  File "C:\Users\Waldo\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\TextureSharing-master\operators.py", line 30, in add_streaming_type_spout
    dir.setup()
  File "C:\Users\Waldo\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\TextureSharing-master\fbs\spout\SpoutDirectory.py", line 16, in setup
    self.update()
  File "C:\Users\Waldo\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\TextureSharing-master\fbs\spout\SpoutDirectory.py", line 23, in update
    sender_names = self.receiver.getSenderList()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'SpoutGL._spoutgl.SpoutReceiver' object has no attribute 'getSenderList'



As for 4.2.1, I can test it, but sadly the bad viewport performance of Eevee next makes it unusable for my project.

**Comment by maybites** [comment]
have you uninstalled the old spout library and installed version 0.1.0?

**Comment by maybites** [comment]
> As for 4.2.1, I can test it, but sadly the bad viewport performance of Eevee next makes it unusable for my project.

EEVEE performance decreased from 4.1.1 to 4.2.1?

**Comment by Waldehyd** [comment]
[Crashlog.txt](https://github.com/user-attachments/files/17025596/Crashlog.txt)

It still crashes, might be very well an edgecase with other addons or settings. A default cube scene seems to works.

Blender 4.2 introduced the new EEVEE Next as default, which at least for my scene using real time camera tracking had a big impact, even with the Raytracing feature disabled.

**Comment by maybites** [comment]
I guess the relevant lines are those:

Stack trace:
blender.exe         :0x00007FF7E5C47100  blender::realtime_compositor::Operation::get_input
blender.exe         :0x00007FF7E5C4A950  blender::realtime_compositor::NodeOperation::compute_preview
blender.exe         :0x00007FF7E5C46E60  blender::realtime_compositor::Operation::evaluate
blender.exe         :0x00007FF7E5C3D7F0  blender::realtime_compositor::Evaluator::evaluate
blender.exe         :0x00007FF7E57651B0  drw_engines_draw_scene
blender.exe         :0x00007FF7E57611C0  DRW_draw_render_loop_ex
blender.exe         :0x00007FF7E5761810  DRW_draw_render_loop_offscreen
blender.exe         :0x00007FF7E6337530  ED_view3d_draw_offscreen
blender.exe         :0x00007FF7E684F870  pygpu_offscreen_draw_view3d
python311.dll       :0x00007FFDD672D710  PyComplex_AsCComplex
python311.dll       :0x00007FFDD6724630  PyBytes_Repeat
python311.dll       :0x00007FFDD6724D80  PyObject_Vectorcall
python311.dll       :0x00007FFDD6849EE0  PyEval_EvalFrameDefault
python311.dll       :0x00007FFDD6849EE0  PyEval_EvalFrameDefault
python311.dll       :0x00007FFDD6724F90  PyFunction_Vectorcall
python311.dll       :0x00007FFDD6724B90  PyVectorcall_Function
python311.dll       :0x00007FFDD6724DE0  PyObject_Call
blender.exe         :0x00007FF7E5AA8000  cb_region_draw
blender.exe         :0x00007FF7E5E58510  ED_region_draw_cb_draw
blender.exe         :0x00007FF7E5ADD5A0  ED_region_do_draw
blender.exe         :0x00007FF7E5666EA0  wm_draw_window_offscreen
blender.exe         :0x00007FF7E5666CD0  wm_draw_window
blender.exe         :0x00007FF7E5666700  wm_draw_update
blender.exe         :0x00007FF7E5631D00  WM_main
blender.exe         :0x00007FF7E5028530  main
blender.exe         :0x00007FF7E78D1B04  __scrt_common_main_seh
KERNEL32.DLL        :0x00007FFE78192560  BaseThreadInitThunk
ntdll.dll           :0x00007FFE794AAF00  RtlUserThreadStart

and 

Python backtrace
  File "C:\Users\Waldo\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\TextureSharing-master\operators.py", line 107 in texshare_capture

## analysis:

blender.exe         :0x00007FF7E684F870  pygpu_offscreen_draw_view3d

is the call of operators.py line 107

but the stack trace shows you are using the realtime compositor. See if the crash still happens with without realtime compositing.

**Comment by Waldehyd** [comment]
Good catch, looks like the compositor was the problem!

**Comment by maybites** [comment]
See if the crash also happens with this script executed:

https://docs.blender.org/api/master/gpu.html#rendering-the-3d-view-into-a-texture

offscreen.draw_view3d is where blender stumbles over in your crash report.

if the crash still happens, then it points to an underlying problem with the offscreen rendering pipeline, and thats something blender developers might be interested in... 

-> https://developer.blender.org/docs/handbook/bug_reports/making_good_bug_reports/
