### ISSUE TITLE
blender Cannot install package: ndi-python

### ISSUE THREAD

**Issue by Realeyz** [maybites/blender.script.spout#42]
This Add-On worked immediately with Sprout, but when I try to install the NDI wheel file, I keep getting this error reported from Blender:
**"Cannot install package: ndi-python"**

<img width="1920" alt="Screenshot 2024-09-22 at 10 47 15 AM" src="https://github.com/user-attachments/assets/514378b0-7df7-479b-ae44-1e2e79fe6baf">

I have installed the current NDI SDK (Install_NDI_SDK_v6_Apple.pkg).
The wheel I am trying to install is:
ndi_python-5.1.1.5-cp311-cp311-macosx_13_0_arm64.whl

I am running on macOS Silicon, Sonoma  14.

Please advise on steps to resolve.  Thank you!

**Comment by maybites** [comment]
Yea, You are right. There is something wrong with the Wheel.

For the time beeing you need to build it yourself: https://github.com/buresu/ndi-python#build
