### ISSUE TITLE
request enhancement spout input

### ISSUE THREAD

**Issue by sasa42** [maybites/blender.script.spout#6]
Thanks for making this.
This is an request for an spout input to a texture for eevee.
Has anyone an idea how this could be done?
e.g.
Spout renders to image texture node in node editor.
Apply material to uv plane.

**Comment by sasa42** [comment]
additional info.
In Unity i use
https://github.com/keijiro/KlakSpout

which has an nice spout sender and receiver implementation.

**Comment by maybites** [comment]
yes, that would be nice. but I was unable to receive any spout texture so far.

the dev branch has a experiments.blend file with scripts that try to attempt this. you could start there...https://github.com/maybites/blender.script.spout/blob/dev/experiments.blend
