### ISSUE TITLE
Streaming Spout from Blender

### ISSUE THREAD

**Issue by Alis939** [maybites/blender.script.spout#7]
Hi guys!
Thank you for this add-on, i need it!
I'm trying to send a streaming output from Blender to Touchdesigner (or Resolume).
I've install all, and i can see the panel 'Streaming Texture' in the Camera proprieties...
But i've two problems, probaly in relation to each other:

1) in the preference, under the voice 'Testing', appear the warning message that says "This plugin works only if the SpoutSDK.pyd is inside '~/scripts/modules'".
This .pyd file is out the 'scripts' folder in Blender, i've follow the instruction, and i've creating another folder, called with the same name 'scripts' with inside two folders ('addons' and 'modules') with the relative files inside.

2) The other programs can detect the name of server 'Camera' but can't see anything.

Thanks for your attention and help! :)))

**Comment by maybites** [comment]
1. the proper setup:

~/scripts/addons/spout/...
~/scripts/modules/SpoutSDK.pyd

that should work...

**Comment by Alis939** [comment]
The following image is the routes folder... Still not working
![Screenshot (108)](https://user-images.githubusercontent.com/58095942/69478391-21e31b80-0df2-11ea-9c40-04732c299c25.png)

And appear the same message
![Screenshot (109)](https://user-images.githubusercontent.com/58095942/69478417-55be4100-0df2-11ea-94a0-f722d28a830d.png)

**Comment by Alis939** [comment]
Oh... okay, it was the buid 2.80 not tha latest... 
in any case i've the same warning message, 
but now it's working!
