### ISSUE TITLE
View port render settings

### ISSUE THREAD

**Issue by PLAN8VR** [maybites/blender.script.spout#8]
Hi, not a bug, but a question - (First thank you so much for releasing this!)

in the Readme it says "The render settings are currently taken from the main 3d View settings", can you tell me where these settings are? I cannot find them!

I have tried manually changing the resolution in the streaming texture width and height boxes, which seems to be allowed, but it appears to kill the stream (just a black screen is received) - Thanks in advance!

**Comment by maybites** [comment]
> in the Readme it says "The render settings are currently taken from the main 3d View settings", can you tell me where these settings are? I cannot find them!

they are set in the viewport through the hovering UI. for example the viewport shading or overlays settings. this unfortunately means the scene is rendered twice, once in the viewport and once to texture, which can be taxing for some gfx cards when rendering EEVEE.

> I have tried manually changing the resolution in the streaming texture width and height boxes, which seems to be allowed, but it appears to kill the stream (just a black screen is received) 

for the time being, just don't do it :-)

I will have a look at this some time in the future with more leisure in my hand..

**Comment by PLAN8VR** [comment]
Hi there, thanks for taking the time to explain. And thanks again for the addon, works perfectly. Thanks!!
