### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by Faluth** [maybites/blender.script.spout#9]
Hi
First i want to apologize for my poor English..

I try to install spout addon on Blender 2.82 but i can't enabled it

![image](https://user-images.githubusercontent.com/66220632/83360760-26c9ee80-a384-11ea-8fa7-479e294d0371.png)

message error :
 Traceback (most recent call last):
  File "D:\Logiciels\blender\2.82\scripts\modules\addon_utils.py", line 351, in enable
    mod = import(module_name)
ModuleNotFoundError: No module named 'blender'

Anyone can help me please?

**Comment by maybites** [comment]
did you install the latest release?

https://github.com/maybites/blender.script.spout/releases/latest

**Comment by Faluth** [comment]
Oh ! it's working i'm so sorry... really... i haven't see that was older release... i was on 1.0

Really thanks you ! :D
